# MySQL database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/movie_recommendation

# Your MySQL username
spring.datasource.username=root
# Your MySQL password
spring.datasource.password=Your DB password

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Backend server port
server.port=8080